apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
  namespace: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test2 
  template:
    metadata:
      labels:
        app: test2
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: test2
        image: arck8sconformance.azurecr.io/samples/demo:v0.1.0
        ports:
        - containerPort: 8080
